export const businessCategories = [
  "Barber",
  "Hair Salon",
  "Tattoo Studio",
  "Nail Artist",
  "Massage Therapist",
  "Personal Trainer",
  "Yoga Instructor",
  "Makeup Artist",
  "Photographer",
  "Therapist / Counselor",
  "Medical / Clinic",
  "Spa & Wellness",
  "Pet Groomer",
  "Coach / Consultant",
  "Cleaning Services",
  "Repair Services",
  "Language Tutor",
  "Music Teacher",
  "Driving Instructor",
  "Other",
];
