import {
  Search,
  Calendar,
  MapPin,
  Star,
  Clock,
  Monitor,
  TrendingUp,
  BarChart3,
  Settings,
  UserCheck,
  Building,
  User,
  Users,
} from "lucide-react";

export const userTypes = [
  {
    icon: Search,
    title: "For Clients",
    description: "Find and book services from trusted professionals near you",
    features: [
      {
        text: "Search local service providers",
        icon: MapPin,
        colors: { bg: "bg-primary/10", text: "text-primary" },
      },
      {
        text: "Compare reviews and pricing",
        icon: Star,
        colors: { bg: "bg-chart-2/10", text: "text-chart-2" },
      },
      {
        text: "Book appointments instantly",
        icon: Clock,
        colors: { bg: "bg-chart-3/10", text: "text-chart-3" },
      },
      {
        text: "Manage your bookings online",
        icon: Monitor,
        colors: { bg: "bg-chart-5/10", text: "text-chart-5" },
      },
    ],
    ctaText: "Find Services",
    ctaRoute: "/search",
    gradient: "from-primary/5 to-chart-2/5",
    iconColor: "text-primary",
    iconBg: "bg-primary/10",
    hoverIconBg: "group-hover:bg-primary/20",
    borderColor: "border-primary/20",
    popular: false,
  },
  {
    icon: Calendar,
    title: "For Individual Professionals",
    description: "Manage your appointments and grow your solo practice",
    features: [
      {
        text: "Create your professional profile",
        icon: User,
        colors: { bg: "bg-chart-1/10", text: "text-chart-1" },
      },
      {
        text: "Manage your schedule efficiently",
        icon: Calendar,
        colors: { bg: "bg-chart-4/10", text: "text-chart-4" },
      },
      {
        text: "Accept online bookings 24/7",
        icon: Clock,
        colors: { bg: "bg-primary/10", text: "text-primary" },
      },
      {
        text: "Track earnings and analytics",
        icon: TrendingUp,
        colors: { bg: "bg-chart-2/10", text: "text-chart-2" },
      },
    ],
    ctaText: "Start Your Practice",
    ctaRoute: "/auth/register/individual",
    gradient: "from-chart-1/5 to-chart-3/5",
    iconColor: "text-chart-1",
    iconBg: "bg-chart-1/10",
    hoverIconBg: "group-hover:bg-chart-1/20",
    borderColor: "border-chart-1/20",
    popular: true,
  },
  {
    icon: Users,
    title: "For Businesses",
    description: "Manage teams, multiple locations, and scale your operations",
    features: [
      {
        text: "Multi-staff scheduling",
        icon: UserCheck,
        colors: { bg: "bg-chart-3/10", text: "text-chart-3" },
      },
      {
        text: "Team performance analytics",
        icon: BarChart3,
        colors: { bg: "bg-chart-5/10", text: "text-chart-5" },
      },
      {
        text: "Client management system",
        icon: Settings,
        colors: { bg: "bg-primary/10", text: "text-primary" },
      },
      {
        text: "Advanced reporting tools",
        icon: Building,
        colors: { bg: "bg-chart-1/10", text: "text-chart-1" },
      },
    ],
    ctaText: "Grow Your Business",
    ctaRoute: "/auth/register/business",
    gradient: "from-chart-3/5 to-chart-5/5",
    iconColor: "text-chart-3",
    iconBg: "bg-chart-3/10",
    hoverIconBg: "group-hover:bg-chart-3/20",
    borderColor: "border-chart-3/20",
    popular: false,
  },
];
